monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Line1__sink"
      }
    ]
    actions = {
      update-props = {
        node.name        = "goxlr_game"
        node.description = "GoXLR Game"
      }
    }
  }
]

